// This file has been generated by Specta. DO NOT EDIT.

import {
  createTauRPCProxy as createProxy,
  type InferCommandOutput,
} from "taurpc";
type TAURI_CHANNEL<T> = (response: T) => void;

export type Collection = {
  id: number;
  producer_id: number;
  collector_id: number | null;
  tank_id: number;
  quantity: string;
  date: string;
};

export type CollectionByCollector = {
  id: number;
  name: string;
  total: string | null;
};

export type CollectionByProducer = {
  id: number;
  name: string;
  total: string | null;
};

export type Collector = { id: number; name: string };

export type IpcError =
  | { type: "DatabaseError" }
  | { type: "InvalidValue"; data: [string, string] };

export type NewCollection = {
  producer_id: number;
  collector_id: number | null;
  tank_id: number;
  quantity: string;
  date: string;
};

export type NewCollector = { name: string };

export type NewProducer = {
  name: string;
  day_shift: boolean;
  night_shift: boolean;
};

export type NewTank = { name: string; capacity: string | null };

export type NewWithdrawal = { tank_id: number; quantity: string; date: string };

export type Producer = {
  id: number;
  name: string;
  day_shift: boolean;
  night_shift: boolean;
};

export type Tank = { id: number; name: string; capacity: string };

export type TankMovByDateRange = {
  date: string;
  total_collections: string;
  total_withdrawals: string;
};

export type Withdrawal = {
  id: number;
  tank_id: number;
  quantity: string;
  date: string;
};

const ARGS_MAP = {
  collections:
    '{"create_collection":["new_collection"],"delete_collection":["collection_id"],"get_collection":["collection_id"],"list_collections":[],"update_collection":["collection_id","collection"]}',
  collectors:
    '{"create_collector":["collector"],"delete_collector":["collector_id"],"get_collector":["collector_id"],"list_collectors":[],"update_collector":["collector_id","collector"]}',
  dashboard:
    '{"get_collection_by_date_range":["start_date","end_date"],"get_collector_data":[],"get_producer_data":[]}',
  producers:
    '{"create_producer":["producer"],"delete_producer":["producer_id"],"get_producer":["producer_id"],"list_producers":[],"update_producer":["producer_id","producer"]}',
  tanks:
    '{"create_tank":["new_tank"],"delete_tank":["tank_id"],"get_tank":["tank_id"],"list_tanks":[],"update_tank":["tank_id","updated_tank"]}',
  withdrawals: '{"create_withdrawal":["new_withdrawal"]}',
};
export type Router = {
  collections: {
    create_collection: (newCollection: NewCollection) => Promise<Collection>;
    delete_collection: (collectionId: number) => Promise<null>;
    get_collection: (collectionId: number) => Promise<Collection>;
    list_collections: () => Promise<Collection[]>;
    update_collection: (
      collectionId: number,
      collection: NewCollection,
    ) => Promise<Collection>;
  };
  collectors: {
    create_collector: (collector: NewCollector) => Promise<Collector>;
    delete_collector: (collectorId: number) => Promise<null>;
    get_collector: (collectorId: number) => Promise<Collector>;
    list_collectors: () => Promise<Collector[]>;
    update_collector: (
      collectorId: number,
      collector: NewCollector,
    ) => Promise<Collector>;
  };
  dashboard: {
    get_collection_by_date_range: (
      startDate: string,
      endDate: string,
    ) => Promise<TankMovByDateRange[]>;
    get_collector_data: () => Promise<CollectionByCollector[]>;
    get_producer_data: () => Promise<CollectionByProducer[]>;
  };
  producers: {
    create_producer: (producer: NewProducer) => Promise<Producer>;
    delete_producer: (producerId: number) => Promise<null>;
    get_producer: (producerId: number) => Promise<Producer>;
    list_producers: () => Promise<Producer[]>;
    update_producer: (
      producerId: number,
      producer: NewProducer,
    ) => Promise<Producer>;
  };
  tanks: {
    create_tank: (newTank: NewTank) => Promise<Tank>;
    delete_tank: (tankId: number) => Promise<null>;
    get_tank: (tankId: number) => Promise<Tank>;
    list_tanks: () => Promise<Tank[]>;
    update_tank: (tankId: number, updatedTank: NewTank) => Promise<Tank>;
  };
  withdrawals: {
    create_withdrawal: (newWithdrawal: NewWithdrawal) => Promise<Withdrawal>;
  };
};

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP);
export type { InferCommandOutput };
